# CC = The C compiler to use
# CFLAGS = The flags to pass to the C compiler
# By putting object files in the dependency list, make knows it must first comple the .c files
CC=gcc
CFLAGS=-I.

hellomake: hellomake.o hellofunc.o
	$(CC) -o hellomake hellomake.o hellofunc.o